// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLcEDtxf4EOzrGvQqrByiSKCdaAWLWf4U',
    appId: '1:899209770467:web:0074e7b87492d2a9801cd6',
    messagingSenderId: '899209770467',
    projectId: 'pesatrackapp',
    authDomain: 'pesatrackapp.firebaseapp.com',
    storageBucket: 'pesatrackapp.appspot.com',
    measurementId: 'G-E0XBY1VJSH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAANrZh_24fsWUjbV1vjrUm1_QQ5HGn5nI',
    appId: '1:899209770467:android:2deee2c40cd1e335801cd6',
    messagingSenderId: '899209770467',
    projectId: 'pesatrackapp',
    storageBucket: 'pesatrackapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc6y1qPiEsDXfVRSVrKiQuezOMZnV5s-k',
    appId: '1:899209770467:ios:3f05003ab8a3aaa7801cd6',
    messagingSenderId: '899209770467',
    projectId: 'pesatrackapp',
    storageBucket: 'pesatrackapp.appspot.com',
    iosClientId: '899209770467-esdt8ujan7j9ne1ioqdfb11pb47dral5.apps.googleusercontent.com',
    iosBundleId: 'com.pesatrack.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc6y1qPiEsDXfVRSVrKiQuezOMZnV5s-k',
    appId: '1:899209770467:ios:3f05003ab8a3aaa7801cd6',
    messagingSenderId: '899209770467',
    projectId: 'pesatrackapp',
    storageBucket: 'pesatrackapp.appspot.com',
    iosClientId: '899209770467-esdt8ujan7j9ne1ioqdfb11pb47dral5.apps.googleusercontent.com',
    iosBundleId: 'com.pesatrack.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLcEDtxf4EOzrGvQqrByiSKCdaAWLWf4U',
    appId: '1:899209770467:web:c9bea97ac60aa26b801cd6',
    messagingSenderId: '899209770467',
    projectId: 'pesatrackapp',
    authDomain: 'pesatrackapp.firebaseapp.com',
    storageBucket: 'pesatrackapp.appspot.com',
    measurementId: 'G-1T199HV3C0',
  );

}